config/routes.rb
SampleApp::Application.routes.draw do
  get "sessions/new"

  resources :users do
    member do # route the URLs for user follow... like: /users/1/following /users/1/followers
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy] #with only option to define actions of sessions
  resources :microposts, :only => [:create, :destroy, :index, :show] #:index is for the search action
  resources :relationships, :only => [:create, :destroy] #routes for the user follow/unfollow relationships
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

  match '/contact', :to => 'pages#contact' # match & route '/about' to the about action in Pages controller
  match '/about', :to => 'pages#about'  # more succinct than "get 'pages/about'"
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

  

end

app/views/shared/_error_messages.html.erb
<!-- change all @user above to object so that we can call render 'shared/error_messages', :object => f.object to use it -->
<% if object.errors.any? %>
	<div id="error_explanation">
		<h2> <%= pluralize(object.errors.count, 'error') %>
 			prohibited this user from being saved:
 		</h2>
 		<p> There were problems with the following fields:</p>
 		<ul>
 			<% object.errors.full_messages.each do |error| %>
 				<li><%= error %></li>
 			<%end%>
		</ul>
	</div>
<%end%>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
	<table class="microposts" summary="User microposts">
		<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
		<!-- this line passes :collection with feed_items, which make render to use the given 'feed_item' partial, to render each item in the collection. (:partial =>... can't be omitted 'cos there is a :collection option.) -->
	</table>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
	<td class="gravatar">
		<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	</td>
	<td class="micropost">
		<span class="user">
			<%= link_to feed_item.user.name, feed_item.user %>
		</span>
		<span class="content"><%= wrap(feed_item.content) %></span>
		<span class="timestamp">
			Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
		</span>
	</td>
	<% if current_user?(feed_item.user) %>
	<td>
		<%= link_to "delete", feed_item, :method => :delete, :confirm => "You sure?", :title => feed_item.content %>
	</td>
	<% end %>
</tr>

app/views/shared/_micropost_form.html (Chou-Mac-VM's conflicted copy 2011-07-25).erb
<script type="text/javascript">
var maxnum = 140
function characterCounter(field,cntfield){ 
	document.getElementById(cntfield).innerHTML = maxnum - document.getElementById(field).value.length;
}
</script>

<%= form_for @micropost do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field"> <!-- use counter to count the character left to 140 in the text_area -->
		<%= f.text_area :content, :id => "micropost_content", 
		:onKeyDown=>"characterCounter('micropost_content','character_count')", 
		:onKeyUp=>"characterCounter('micropost_content','character_count')" %>
	</div>
	<span id="character_count">
		<script>document.write(maxnum)</script>
	</span> &nbsp characters left. <br>
	
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/shared/_micropost_form.html.erb
<script type="text/javascript">
var maxnum = 140
function characterCounter(field,cntfield){ 
	document.getElementById(cntfield).innerHTML = maxnum - document.getElementById(field).value.length;
}
</script>

<%= form_for @micropost do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field"> <!-- use counter to count the character left to 140 in the text_area -->
		<%= f.text_area :content, :id => "micropost_content", 
		:onKeyDown=>"characterCounter('micropost_content','character_count')", 
		:onKeyUp=>"characterCounter('micropost_content','character_count')" %>
	</div>
	<span id="character_count">
		<script>document.write(maxnum)</script>
	</span> &nbsp characters left. <br>
	
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/shared/_stats.html.erb
<!-- this partials used to show the counts of following & follower in Home and profile page -->
<% @user ||= current_user %> <!-- this does nothing when @user is not nil(on a progile page), but when it is(on the Home page) it set @user to the current user -->
<div class="stats">
	<table summary="User stats">
		<tr>
			<td>
				<a href="<%= following_user_path(@user) %>">
					<span id="following" class="stat"> <!-- id is for the Ajax implementation -->
						<%= @user.following.count %> following
					</span>
				</a>
			</td>
			<td>
				<a href="<%= followers_user_path(@user) %>">
					<span id="followers" class="stat">
						<%= pluralize(@user.followers.count, "follower") %>
					</span>
				</a>
			</td>
		</tr>
	</table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
	<a href="<%= user_path(current_user) %>">
		<%= gravatar_for current_user, :size => 30 %>
		<span class="user_name">
			<%= current_user.name %>
		</span>
		<span class="microposts">
			<%= pluralize(current_user.microposts.count, "micropost") %>
		</span>
	</a>
</div>