config/routes.rb
SampleApp::Application.routes.draw do
  get "sessions/new"

  resources :users do
    member do # route the URLs for user follow... like: /users/1/following /users/1/followers
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy] #with only option to define actions of sessions
  resources :microposts, :only => [:create, :destroy, :index, :show] #:index is for the search action
  resources :relationships, :only => [:create, :destroy] #routes for the user follow/unfollow relationships
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

  match '/contact', :to => 'pages#contact' # match & route '/about' to the about action in Pages controller
  match '/about', :to => 'pages#about'  # more succinct than "get 'pages/about'"
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

  

end

app/views/pages/_home_not_signed_in.html.erb
<h1>Sample App</h1>
<p>
	this is a home page for the 
	<a href="http://railstutorial.org/">Ruby on Rails Tutorials</a>
	sample application.
</p>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/pages/_home_signed_in.html.erb
<table class="front" summary="For signed-in users">
	<tr>
		<td class="main">
			<h1 class="micropost">What's up?</h1>
			<%= render 'shared/micropost_form' %>
			<%= render 'shared/feed' %>
		</td>
		<td class="sidebar round">
			<%= render 'shared/user_info' %>
			<%= render 'shared/stats' %> <!-- to show the count of follower&following -->
		</td>
	</tr>
</table>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencast to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
	contact ruby on rails tutorial about the sample app at the
	<a href="http://railstutorial.org/feedback">feedback page</a>
	sample application.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
	Get help on Ruby on rails at the <a href="http://railstutorial.org/help">Rails tutorial help page</a>
	Thanks.
</p>

app/views/pages/home.html.erb
<% form_tag microposts_path, :method => 'get' do %> <!-- search bar for the micropost -->
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search all posts", :name => nil %>
	</p>
<% end %>
<% unless current_user.nil? %>
<% form_tag micropost_path(current_user), :method => 'get' do %> <!-- search bar for the micropost -->
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search my posts", :name => nil %>
	</p>
<% end %>
<% end %>

<% if signed_in? %> <!-- add microposts creation form to homepage -->
	<%= render 'pages/home_signed_in' %> <!-- the path relative to views dir should be used (the pages/ ) -->
<% else %>
	<%= render 'pages/home_not_signed_in' %>
<% end %>

<table cellspacing="0" cellpadding="0" border="0"><tr><td><iframe src="http://www.map-generator.net/extmap.php?name=Spot&amp;address=10%20market%20st%2C%20san%20francisco&amp;width=500&amp;height=400&amp;maptype=map&amp;zoom=14&amp;hl=en&amp;t=1311888850" width="500" height="400" marginwidth="0" marginheight="0" frameborder="0" scrolling="no"></iframe></td></tr></table><!-- Do not change code! -->