config/routes.rb
SampleApp::Application.routes.draw do
  get "sessions/new"

  resources :users do
    member do # route the URLs for user follow... like: /users/1/following /users/1/followers
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy] #with only option to define actions of sessions
  resources :microposts, :only => [:create, :destroy, :index, :show] #:index is for the search action
  resources :relationships, :only => [:create, :destroy] #routes for the user follow/unfollow relationships
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

  match '/contact', :to => 'pages#contact' # match & route '/about' to the about action in Pages controller
  match '/about', :to => 'pages#about'  # more succinct than "get 'pages/about'"
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

  

end

app/views/layouts/_flash_notice.html.erb
<% flash.each do |key,value| %> <!-- show the loging flash -->
	<!-- <div class="flash <%= key %>"><%= value %></div> -->
	<%= content_tag(:div, value, :class => "flash #{key}")%> <!-- same thing with above -->
<% end %>

app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<ul>
			<li><%= link_to 'about', about_path %></li>
			<li><%= link_to 'contact', contact_path %></li>
			<li><%= link_to 'news', 'http://news.railstutorial.org/' %></li>
			<li><%= link_to 'Rails tutorial', 'http://www.railstutorial.org' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<% if signed_in? %>
			<li><%= link_to "Users", users_path %></li>
			<li><%= link_to "#{current_user.name}'s Profile", current_user %></li> 
			<li><%= link_to "Setting", edit_user_path(current_user) %></li>
			<% end %>
			<li><%= link_to "Help", help_path %></li>
			<% if signed_in? %> <!-- adapt layout to user signed-in status -->
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
			<% else %>
			<li><%= link_to "Sign in", signin_path %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %> <!--this line for screen-->
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %> <!--this line for print-->
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
		<%= javascript_include_tag :defaults %> <!-- include the default rails javascript lib -->
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				<%= render 'layouts/flash_notice' %><!-- show the loging flash -->
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %><!-- debug msg on site -->
		</div>
	</body>
</html>